#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_AP_SSID "Ambient-C3"
#define APP_AP_PASSWORD "ambient1234"
#define APP_AP_CHANNEL 6
#define APP_AP_MAX_CLIENTS 4
#define APP_AP_IP "192.168.4.1"

#define APP_WIFI_SCAN_INTERVAL_MS 30000
#define APP_WIFI_SCAN_MAX_APS 32
#define APP_BLE_SCAN_INTERVAL_MS 30000
#define APP_BLE_SCAN_DURATION_MS 5000
#define APP_TEMP_INTERVAL_MS 10000
#define APP_WEB_REFRESH_MS 2000
#define APP_STATE_COOLDOWN_MS 60000
#define APP_STALE_TIMEOUT_MS 90000
#define APP_RSSI_HISTORY 8
#define APP_MAX_TRACKED_DEVICES 64

#define APP_QUIET_MAX_DEVICES 2
#define APP_QUIET_MAX_VARIANCE 9.0f
#define APP_ACTIVE_MIN_DEVICES 8
#define APP_ACTIVE_MIN_VARIANCE 36.0f

#define APP_LED_GPIO 8
#define APP_LED_COUNT 1

#endif
